import {
  AchMilestone,
  AchPiggy,
  AchCoinStack,
  AchChest,
  AchMedal,
  AchRunner,
  AchCalendar,
  AchHammer,
  AchCoffee,
  AchBitcoin,
  AchHouse,
  AchFlag,
  AchSeed,
  AchCrown,
  AchExchange,
  AchEye,
  AchTurtle,
  AchRabbit,
  AchRooster,
  AchMoonOrBust,
  AchCake,
  AchClock,
  AchAirplane,
  AchID,
  AchShieldEuro,
  AchBank,
  AchDividend,
  AchFruitBasket,
  AchMusketeers,
  AchPenny,
  AchDayTrader,
  AchLedger,
  AchBat,
  AchPendu,
  IconTrophy,
  type IconProps,
} from "@/components/icons";

type CartoonIcon = (p: IconProps) => React.ReactNode;

/**
 * Mappe la clé `icon` (nom Lucide stocké dans le catalogue) vers un picto
 * cartoon de la DA. Fallback : AchMedal.
 */
const MEDAL_ICON_BY_KEY: Record<string, CartoonIcon> = {
  Footprints: AchRunner,
  ShoppingCart: AchExchange,
  Coffee: AchCoffee,
  Activity: AchDayTrader,
  ListOrdered: AchLedger,
  Repeat: AchExchange,
  Hammer: AchHammer,
  Construction: AchHammer,
  Boxes: AchChest,
  Apple: AchFruitBasket,
  Carrot: AchPiggy,
  Milestone: AchMilestone,
  Medal: AchMedal,
  BarChart2: AchDayTrader,
  ShieldCheck: AchShieldEuro,
  Star: AchMedal,
  Flag: AchFlag,
  Glasses: AchEye,
  Trophy: IconTrophy,
  Sprout: AchSeed,
  Swords: AchMusketeers,
  CircleSlash: AchPenny,
  Bitcoin: AchBitcoin,
  Banknote: AchBank,
  Rocket: AchMoonOrBust,
  Flame: AchPendu,
  TrendingUp: AchDayTrader,
  HandCoins: AchDividend,
  Home: AchHouse,
  Building2: AchBank,
  Crown: AchCrown,
  Turtle: AchTurtle,
  Bed: AchClock,
  Rabbit: AchRabbit,
  PiggyBank: AchPiggy,
  Shield: AchShieldEuro,
  UserCheck: AchID,
  Plane: AchAirplane,
  Telescope: AchEye,
  Sparkles: AchCoinStack,
  BookOpen: AchLedger,
  ScrollText: AchLedger,
  CalendarDays: AchCalendar,
  Cake: AchCake,
  TreePine: AchSeed,
  Sunrise: AchClock,
  Brain: AchEye,
  Moon: AchMoonOrBust,
  TrendingDown: AchBat,
  AlertTriangle: AchPendu,
  Dices: AchPenny,
  Briefcase: AchBank,
  Target: AchPenny,
  Bird: AchRooster,
};

export function getMedalIcon(key: string): CartoonIcon {
  return MEDAL_ICON_BY_KEY[key] ?? AchMedal;
}
